- hosts: localhost
  connection: local
  tasks:
    - name: Launch cloudformation for Chef extension
      cloudformation:
        stack_name: "ansible-cloudformation"
        state: "present"
        region: "{{ lookup('env','AWS_REGION') }}"
        disable_rollback: true
        template: "service.template"
        template_parameters:
          KeyName: "{{ lookup('env','AWS_KEYPAIR') }}"
          InstanceType: "t2.large"
          EnvironmentName: "ChefServer"
          EnvironmentSubnet: "{{ lookup('env','AWS_SUBNET_ID') }}"
          VPCId: "{{ lookup('env','AWS_VPC_ID') }}"
          InboundCIDR: "0.0.0.0/0"
        tags:
          Stack: "chef-stack"
      register: cf_out

    - debug: var=cf_out.stdout_lines

    - name: Copy cloudformation facts into a file
      copy: content={{ cf_out }} dest=./cf_out.json