- hosts: localhost
  connection: local
  tasks:
    - name: Launch cloudformation for Chef extension
      cloudformation:
        stack_name: "ansible-cloudformation"
        state: "present"
        region: "{{ lookup('env','AWS_REGION') }}"
        disable_rollback: true
        template: "service.template"
        template_parameters:
          KeyName: "{{ lookup('env','AWS_KEYPAIR') }}"
          InstanceType: "t2.large"
          EnvironmentName: "ChefServer"
          EnvironmentSubnet: "{{ lookup('env','AWS_SUBNET_ID') }}"
          VPCId: "{{ lookup('env','AWS_VPC_ID') }}"
          InboundCIDR: "0.0.0.0/0"
        tags:
          Stack: "chef-stack"
      register: cf_out

    - debug: var=cf_out

    - name: Copy all the cloudformation output facts into a file
      copy: content={{ cf_out }} dest=./cf_out.json

    - name: Copy the ip address attributes of the facts into a file
      copy: content={{ cf_out["stack_outputs"]["EC2InstancePrivateIp"] }} dest=./instance_ip.txt